---
- name: Update apt cache.
  apt: update_cache=true
  become: yes

- name: Install apt packages.
  apt: name={{item}} state=installed
  with_items:
    - apt-transport-https
    - ca-certificates
  become: yes

- name: Add the new GPG key.
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  become: yes

- name: Add an entry for your Ubuntu operating system.
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list
  become: yes

- name: Update apt cache.
  apt: update_cache=true
  become: yes

- name: Purge the old repo if it exists.
  apt: name=lxc-docker state=absent
  become: yes

- name: Update apt cache.
  apt: update_cache=true
  become: yes

- name: Check kernel version.
  shell: uname -r
  register: kv

- name: Install the recommended package.
  apt: name={{item}} state=installed
  with_items:
    - linux-image-extra-{{kv.stdout}}
    - apparmor
    - docker-engine
  become: yes

- name: Create docker group.
  group: name=docker state=present
  become: yes

- name: Add {{user}} to docker group.
  user: name={{user}} group=docker append=yes
  become: yes
